name: add github member

on:
  repository_dispatch:
    types: [add_github_member]

jobs:
  add_github_member:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Configure for Git
        run: |
          git config --global user.email  'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: add a new member
        env:
          NEW_MEMBER: ${{ github.event.client_payload.member }}
        run: |
          echo "- ${NEW_MEMBER}" >> files/users.yml
          NOW=$(date +%Y%m%d%H%M%s)
          BRANCHNAME="add_new_member_${NOW}"
          git checkout -b $BRANCHNAME
          git add files/users.yml
          git commit -m "add new member on ${NOW}"
          git push origin $BRANCHNAME
          gh pr create --head $BRANCHNAME \
            --title "add new member on ${NOW}" \
            --body "This PR created by GitHub Actions.\nsee: https://medpeer.esa.io/posts/29573" \
            --reviewer medpeer-dev/sre
