name: add github member

on:
  repository_dispatch:
    types: [add_github_member]

jobs:
  add_github_member:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Configure for Git
        run: |
          git config --global user.email  'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Create a new file to generate access keys
        env:
          NEW_MEMBER: ${{ github.event.client_payload.member }}
        run: |
          echo "- ${NEW_MEMBER}" >> files/users.yml
