name: add github member

on:
  repository_dispatch:
    types: [add_github_member]

jobs:
  add_github_member:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Run with payload
        run: echo "member:${{ github.event.client_payload.member }}"
